### ISSUE TITLE
Cannot use in unity 2020.3.14

### ISSUE THREAD

**Issue by roger-creus** [steve3003/unity-profiler-data-exporter#11]
Hello,

I have cloned the repo, imported the folder to unity project assets, ran profiler and paused it to run data exporter. I get the following error and the data exporter tab is empty:

InvalidCastException: Specified cast is not valid.
ProfilerDataExporter.SplitterState..ctor (System.Single[] relativeSizes, System.Int32[] minSizes, System.Int32[] maxSizes) (at Assets/unity-profiler-data-exporter/UnityWrappers/SplitterState.cs:31)

Any clue?

Thank you!

**Comment by stepsani** [comment]
Hi, how did you solve this issue?

**Comment by roger-creus** [comment]
I did not use this profile exporter in the end, I used the Unity package called ProfilerAnalyzer, which allows to export CSV data files from the profiler.

**Comment by stepsani** [comment]
Thanks for your answer. I took a look at it and I can’t seem to find a way
to export the Memory data. For example, textures, size ecc.
