### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by TheMeanFiddler** [steve3003/unity-profiler-data-exporter#2]
Assets/Editor/unity-profiler-data-exporter-master/ProfilerDataExporter.cs(89,65): error CS0411: The type arguments for method `System.Linq.Enumerable.Select<TSource,TResult>(this System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource,int,TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly

How do I fix this? Thanks

**Comment by TheMeanFiddler** [comment]
OK I fixed it by putting the correct type arguments. There was another one in StatsCalculatorBase line 54

Now Its running but it seems to want to calculate every single property
I'm on Unity 5.4.5

**Comment by steve3003** [comment]
The compilation error should be fixed with the latest commit.
Yes it calculates every property and I know in some cases you want to avoid doing it, especially if you are  deep profiling.
I plan to add an option to filter the properties to calculate.
