### ISSUE TITLE
How about adding mobile platform support?

### ISSUE THREAD

**Issue by Learningm** [steve3003/unity-profiler-data-exporter#5]
Hi, would you have plan to expand to mobile platform such as android?

**Comment by steve3003** [comment]
Hi, I'm not sure what you mean. Unity already allows you to connect the profiler to a mobile phone, then you can use this tool on that data.

**Comment by Learningm** [comment]
> Hi, I'm not sure what you mean. Unity already allows you to connect the profiler to a mobile phone, then you can use this tool on that data.

Hi, Thanks for the rely. I am new to Unity, when I switch platform to android,  there exists some compile errors, it seems that some tools are only available in Editor Mode, I try to fix the error under android platform but I didn't work out, No ideas how to fix the compile error, Thanks!

**Comment by steve3003** [comment]
I've just tried switching to android platform on Unity 2018.3.12f1 and I don't get any compiler errors. Can you post the errors you are getting please?
