### ISSUE TITLE
DrawCall count

### ISSUE THREAD

**Issue by resetme** [steve3003/unity-profiler-data-exporter#7]
Hi, 

I have done a very similar tool that create a json file, it also compare many profiler using unity editor or web angular. is really helpful!
In my tool I also have total average FPS, and today I was trying to add total average DrawCall but my code always give me 0 draw calls.

I google for some similar tools and I found this one, i checked the json export and the draw call value is 0 or N/A as well.

Any idea why we can't get the draw call count?

**Comment by bbi-dennindalke** [comment]
Did you check if you have the GPU profiler enabled and the Graphics Jobs feature disabled? Sometimes the Graphics jobs make the profiler unable to capture rendering data.

**Comment by steve3003** [comment]
Yeah it looks like you need to have the GPU profiler enabled to get the `DrawCalls` column from `ProfilerProperty`.
You could use `ProfilerDriver.GetOverviewText(ProfilerArea.Rendering, frameNumber)` to get the text shown on the rendering profiler instead and parse that to get the draw calls without enabling the GPU profiler.
